version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn run test
            - run: yarn chromatic test --app-code=<app-code> --exit-zero-on-changes
workflows:
    build-and-test:
      jobs:
        - build-and-test